# Generated by Django 4.1.2 on 2024-12-03 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comm_to_repl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.comments'),
        ),
    ]
