# Generated by Django 4.1.2 on 2024-12-03 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_data_posted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueticket',
            name='data_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.data'),
            preserve_default=False,
        ),
    ]
