# Generated by Django 4.1.2 on 2024-12-04 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_comments_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='comments',
            name='likes',
        ),
        migrations.AlterField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comments',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
