# Generated by Django 4.1.2 on 2024-12-04 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_comments_comm_to_repl_alter_comments_post_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PushDataRequest',
        ),
    ]
