# Generated by Django 4.1.2 on 2024-12-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_commentlike_comments_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueticket',
            name='status',
            field=models.SmallIntegerField(default=None),
            preserve_default=False,
        ),
    ]
