# Generated by Django 4.1.2 on 2024-12-04 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_issueticket_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issueticket',
            name='status',
        ),
    ]
