# Generated by Django 4.1.2 on 2024-12-04 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_remove_issueticket_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueStatus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('status_description', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='issueticket',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.issuestatus'),
        ),
    ]
